inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - '_site/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - '.git/**/*'
    - 'bin/**/*'
    - '*.gemspec'

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
  AllowedMethods:
    - configure
    - describe
    - context
    - task

Layout/LineLength:
  Max: 120
  Exclude:
    - 'Rakefile'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'Rakefile'

Gemspec/RequiredRubyVersion:
  Enabled: false
