# Encoding and Core Settings
encoding: UTF-8
strict_front_matter: true

# Jekyll Configuration
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-minifier

# Analytics and Performance Configuration
google_analytics: G-5N6HK2SMN0
google_analytics_options:
  siteSpeedSampleRate: 100
  anonymizeIp: true
  cookieDomain: auto

# Site Settings
page_title: "Baseball Bound - College Baseball Recruiting Assistant App | Find Your Perfect Program"
title: "Baseball Bound - College Baseball Recruiting Assistant App | Find Your Perfect Program"
description: "Baseball Bound helps athletes own their college baseball recruiting process with real-time access to over 1,200 NCAA, NAIA, and JUCO programs. Get coach contacts, program stats, and recruiting deadlines all in one place."
keywords: "college baseball recruiting, baseball recruiting app, NCAA baseball programs, NAIA baseball, JUCO baseball, college baseball coaches, athletic recruiting"
tagline: "Streamline Your College Baseball Recruiting Journey"
site_name: "Baseball Bound"
author: AllTeamz

# App Info
ios_app_id: 1502937685
ios_app_country: us
app_icon: /assets/bbicon.jpeg
app_name: Baseball Bound
app_price: ""
app_description: "Own the recruiting process by putting every coach in your pocket!"
enable_smart_app_banner: true

# Social Media and Contact
your_name: AllTeamz
your_link: https://allteamz.com
your_city: Los Angeles
email_address: ryan@allteamz.com
facebook_username: allteamz
instagram_username: softballbound_app
twitter_username: allteamz
github_username:
youtube_username:
logo: /assets/bbicon.jpeg
image: assets/bbicon.jpeg

# Social Media Meta
og_type: website
og_image: assets/bbicon.jpeg
og_site_name: "Baseball Bound"
twitter_card: summary_large_image
twitter_creator: "@allteamz"
twitter_site: "@allteamz"

# Redirect Configuration
defaults:
  - scope:
      path: "assets/screenshot"
    values:
      screenshot: true
  - scope:
      path: ""
    values:
      layout: "default"
      redirect_from:
        - /app
        - /ios
        - /download
        - /install
        - /baseball
        - /recruiting
        - /college-baseball
        - /ncaa
        - /naia
        - /juco
        - /baseballbound
        - /baseball-bound
        - /baseball_bound
        - /baseballapp
        - /baseball-app
        - /recruit
        - /recruiting-app
        - /college
        - /coaches

# Asset Paths
screenshot_path: "assets/screenshot/baseballboundscreen.jpeg"
assets_path: "assets"

# Asset Caching and Processing
assets:
  compress:
    css: true
    js: true
  cache: true
  cdn: false
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true
  source_maps: false
  destination: "/assets"
  compression: true
  gzip: false

# Performance Settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

jekyll-minifier:
  exclude: ['*.xml']
  uglifier_args:
    harmony: true
  compress_css: true
  compress_javascript: true
  js_compressor: uglifier
  css_compressor: sass
  html_compressor: zlib

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# SASS Configuration
sass:
  style: compressed
  implementation: sass-embedded
  sass_dir: _sass
  load_paths:
    - _sass
    - node_modules

# Encoding and Processing
encoding: UTF-8
strict_front_matter: true
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

# Exclude files from build
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
  - node_modules
  - tmp
  - .sass-cache
  - .jekyll-cache
  - .git

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: /assets/baseball_header.jpeg
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: /assets/black.png
body_background_color: "#ffffff"

screenshot_path: /assets/screenshot/baseballboundscreen.jpeg

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

# Feature List
features:
  - title: Complete College Database
    description: Access detailed information for over 1,200 NCAA, NAIA, and JUCO baseball programs. Find your perfect fit with comprehensive program data.
    fontawesome_icon_name: school
    
  - title: Direct Coach Contact
    description: Connect directly with college coaches through verified contact information including phone, email, and program websites.
    fontawesome_icon_name: phone

  - title: Smart Program Filtering
    description: Easily find schools matching your criteria by state, division, conference, or name with our intuitive interface.
    fontawesome_icon_name: sort

  - title: Academic Success Metrics
    description: Make informed decisions with key statistics on graduation rates, student retention, average GPAs, and post-graduation success.
    fontawesome_icon_name: graduation-cap

  - title: Real-time Updates
    description: Stay current with automatic updates on coach changes, program information, and recruiting deadlines - no manual updates needed.
    fontawesome_icon_name: marker
  
  - title: Recruiting Timeline Alerts
    description: Never miss important NCAA and NAIA deadlines with smart notifications that keep your recruiting journey on track.
    fontawesome_icon_name: bell

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Jekyll Feed Configuration
feed:
  path: feed.xml
  posts_limit: 20
  excerpt_only: true

# Jekyll SEO Tag Configuration
social:
  name: Baseball Bound
  links:
    - https://twitter.com/allteamz
    - https://www.facebook.com/allteamz
    - https://www.instagram.com/softballbound_app

# Additional SEO Settings
lang: en_US
locale: en_US
url: "https://allteamz.com"
baseurl: ""
